enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

patches-version = "v2.224.1-dev.5"
integrations-version = "v0.151.1-dev.3"

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea Reddit ReVanced"
build-mode = "both"
