enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

patches-version = "v2.225.0-dev.13"
integrations-version = "v0.152.0-dev.8"
cli-source = "inotia00/revanced-cli"

[Reddit]
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea Reddit ReVanced"
build-mode = "both"