enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

patches-version = "v2.229.0"
integrations-version = "v0.156.0"
cli-source = "inotia00/revanced-cli"

[Reddit]
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea Reddit ReVanced"
build-mode = "both"