enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

patches-version = "v2.225.0-dev.13"
integrations-version = "v0.152.0-dev.8"
cli-source = "inotia00/revanced-cli"

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea ReVanced Afn Red Icon"
build-mode = "both"
included-patches = "'Custom branding icon YouTube' 'MaterialYou'"
excluded-patches = "'Theme'"
version = "19.16.39"

[YouTube Music]
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea ReVanced Afn Red Icon"
build-mode = "both"
included-patches = "'Custom branding icon YouTube Music'"
excluded-patches = "'Amoled'"
version = "6.51.52"