enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app


patches-version = "v2.226.0-dev.11"
integrations-version = "v0.153.0-dev.5"
cli-source = "inotia00/revanced-cli"

[Reddit]
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "anddea Reddit ReVanced"
build-mode = "both"